repos:
  - repo: local
    hooks:
      - id: groovy-lint
        name: Groovy Lint
        language: docker_image
        entry: nvuillam/npm-groovy-lint:latest npm-groovy-lint
        stages: [commit]