repos:
  - repo: local
    hooks:
      - id: groovy-lint
        name: Groovy Lint
        entry: docker run --rm -v $(pwd):/data nvuillam/npm-groovy-lint groovy-lint /data --fix
        language: system
        stages: [commit]
